### ISSUE TITLE
Issue box going out of bound

### ISSUE THREAD

**Issue by arjunvijayanathakurup** [github/explore#1013]
In the explore page, one of the issues containing a link is getting out of bounds of the container. Every other issues are in the bound of the container, but one of them stands out.

![image](https://user-images.githubusercontent.com/25499018/64491021-d86a4200-d280-11e9-96dd-af3421917545.png)

**Comment by slgraff** [comment]
We've received a report of this from a user with Firefox on Linux Mint.
https://github.zendesk.com/agent/tickets/374085

**Comment by kenyonj** [comment]
This issue has been resolved. Thanks again for the report @arjunvijayanathakurup !

**Comment by arjunvijayanathakurup** [comment]
Glad I could help
