### ISSUE TITLE
Unable to change the state of star button to unstar on trending page

### ISSUE THREAD

**Issue by owen800q** [github/explore#1014]
when on page https://github.com/trending, Once I star a repository and refresh the page again, the star button did not change to unstar. This issue appear on both chrome and firefox
```
OS: ubuntu 18.04
Chrome: Version 76.0.3809.132 (Official Build) (64-bit)
Firefox: 69.0 (64-bit)
```
![Peek 2019-09-09 10-28](https://user-images.githubusercontent.com/19252045/64499858-5b28e680-d2ed-11e9-8fe2-0bf4f54fa3d5.gif)

**Comment by kenyonj** [comment]
@owen800q Thank you for this report! We are looking into it right now.

**Comment by kenyonj** [comment]
This issue has been fixed.
