### ISSUE TITLE
Coding dengan Framework

### ISSUE THREAD

**Issue by hartono500** [github/explore#1039]
/*-------------------------------
Membuat bot Telegram sederhana 
dengan Telegraf Framework ~ NodeJS
--------------------------------*/
 
const Telegraf = require('telegraf')
const bot = new Telegraf('ISI TOKEN')
 
bot.on('text', (ctx) =&gt; {
 console.log(ctx.message)
 
 if (ctx.message.text == '/start') {
    ctx.replyWithHTML(
     '&lt;i&gt;Welcome&lt;/i&gt; &lt;b&gt;'+ ctx.from.first_name +'&lt;/b&gt;',
  {'reply_to_message_id':ctx.message.message_id})}
 
 if (ctx.message.text == '/hey') {
    ctx.replyWithMarkdown(
     'Hey *'+ ctx.from.first_name +'*',
  {'reply_to_message_id':ctx.message.message_id})}
 
 })
 
bot.startPolling()

**Comment by MKANDJN** [comment]
Jennifer
