### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by yury653** [github/explore#1067]
help me please anyone.in the morning the icon through which I enter keybase disappeared and I can’t enter it now, I rebooted the computer and reinstalled the file, it doesn’t appear. How do I enter keybase and what should I do?

**Comment by TomasRoj** [comment]
@yury653 I am not pretty sure if this is the right place to ask about your problem. PLease try to ask on github forum and explain it more.

**Comment by yury653** [comment]
> @yury653 I am not pretty sure if this is the right place to ask about your problem. PLease try to ask on github forum and explain it more.
nobody answers anywhere
