### ISSUE TITLE
Add hactoberfest to Events section

### ISSUE THREAD

**Issue by TomasRoj** [github/explore#1117]
Add hactoberfest 2019 event to events section. This can get many new people to open-source and its good for github.

**Comment by braveheartt** [comment]
Thank

**Comment by shanelennad** [comment]
Ok

**Comment by shaz0104** [comment]
Nice

**Comment by rafadastan** [comment]
Ok

**Comment by Diger2010** [comment]
👍

**Comment by talsafran** [comment]
Hi @TomasRoj! Sorry that this got buried! This was a great suggestion, and we've supported Hacktoberfest in the past. But I think we're seeing this too late 😢 

Thank you ✨
