### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by macleod7** [github/explore#1178]
<form action="https://bitpay.com/checkout" method="post">
  <input type="hidden" name="action" value="checkout" />
  <input type="hidden" name="posData" value="" />
  <input type="hidden" name="data" value="MiUVj3q3RSDJOcOXM7mD0puMTYArpw+EyCcVg6c690L7nPazAUtzgIO6I7eRGwB6OPP+JRsOG7plcomM+K/1+lV1wRvg15VdzXqRo/m7j9yX75bgttQwmVRxaZJ8f395vxnMwtLEQId3kMfhcxp62rOvapmuxyor6LL4jsIjNW6uBxN3WMR+Dg05UNL9MlyB" />
  <input type="image" src="https://bitpay.com/cdn/en_US/bp-btn-pay-currencies.svg" name="submit" style="width: 210px" alt="BitPay, the easy way to pay with bitcoins.">
</form>

**Comment by keithbrianptomo** [comment]
?
