### ISSUE TITLE
Locked out of my account due to IP address whitelisting

### ISSUE THREAD

**Issue by ohoward83** [github/explore#1180]
If I attempt to log on the web, I am denied access and a few seconds later I receive the following email: An IP address that is not on your whitelist attempted to access your account. If I attempt any API call, the response I get is: HTTP 403 Access forbidden.

I contacted SendGrid support (ticket 2854686) but they want to verify account ownership and the only way they want me to prove ownership is by sending an email with a given subject from my SendGrid account to an address they specified. Obviously, I can't do that since I'm locked out. It's a catch 22: they won't help me until I can prove ownership and I can't prove ownership until they help me!

Is there a way find out if they have another owner of the account listed so they can vouch for the fact that I am indeed the legitimate owner of my account

**Comment by xIITOXAIIx** [comment]
fck..I don't understand nothing here!please sorry for this...
