### ISSUE TITLE
Hi i am facing an error in zodiacpress wordpress plugin as mentioned blow I am using divi theme right now with it

### ISSUE THREAD

**Issue by yasupanju** [github/explore#1196]
here is my page link
 https://astrologielounge.com/dein-horoskop/  
   you may test it when i put data and click on submit the java script code show an error

Error from search console

zp.min.js?ver=2.0.2:1 Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of null

at XMLHttpRequest.n.onload (zp.min.js?ver=2.0.2:1)

n.onload @ zp.min.js?ver=2.0.2:1

load (async)

(anonymous) @ zp.min.js?ver=2.0.2:1

**Comment by KaaSHH** [comment]
.github/ISSUE_TEMPLATE/bug_report.md
