### ISSUE TITLE
Topic result extremely reduced since some days?

### ISSUE THREAD

**Issue by svenhb** [github/explore#1214]
If I look for topic #grbl I got a few pages of repos listed - since years - ordered by amount of stars (nice ranking), since friday I got a result of only 8 repos in strange order.

**Comment by carlself** [comment]
it seems that all the topics show only 8 repos.

**Comment by LucaGanio** [comment]
it seems that also the chance to choose the programming language of interest has gone missing...
wish someone fixes these issues soon!!!!

**Comment by btzr-io** [comment]
Now I only see my repository on one topic: `comic-books` at the end of the results :disappointed:

**Comment by danffer2019** [comment]
发现了

鱼生有你

________________________________

**Comment by evdcush** [comment]
The topics seems to have been recently broken.



There is no way to sort or filter results, and only an irrelevantly small subset of projects are displayed (in apparently random order) for any given topic.


Why change topics?


 

You can see that there were 1,832 repos with the 'robotics' tag, according to wayback cache for Mar 08 2018: https://web.archive.org/web/20180308134624/https://github.com/topics/robotics

Needless to say, you can also filter by language and sort (ie, *explore* repos).


But the current page (https://github.com/topics/robotics) only shows 8 repos?

**Comment by mhterry** [comment]
https://twitter.com/maxwellterry/status/1192812733630165000

**Comment by LucaGanio** [comment]
it seems to be fixed now

**Comment by eman291** [comment]
https://web.archive.org/web/20180308134624/https://github.com/topics/robotics

**Comment by kenyonj** [comment]
This issue has been resolved. Thank you for the report.
