### ISSUE TITLE
Topic results should start with projects that actually have the topic

### ISSUE THREAD

**Issue by ligi** [github/explore#1216]
see here: 
![image](https://user-images.githubusercontent.com/111600/68647138-6d7b0700-0560-11ea-968d-5789bf82fd3c.png)

the first result has ENS in the description but not in the topic. It would be better if either:
 - only results are shown where the projects have the topic 
 - the results that have the topic in the description are shown *after* the projects that have the topic in their topic list

**Comment by kenyonj** [comment]
I don't believe this is an issue any longer. Thank you for the report.
