### ISSUE TITLE
Explore tab says the wrong amount of commits

### ISSUE THREAD

**Issue by nm17** [github/explore#1234]
![Screenshot from 2019-11-17 20-27-58](https://user-images.githubusercontent.com/23419131/69010612-d6a4b500-097a-11ea-94e0-8db15965a810.png)
![Screenshot from 2019-11-17 20-28-12](https://user-images.githubusercontent.com/23419131/69010611-d6a4b500-097a-11ea-8f84-7a7051991495.png)

**Comment by Tuanhta** [comment]
Hat

**Comment by Tuanhta** [comment]
Hahahha

**Comment by kenyonj** [comment]
This issue has been resolved. Thanks for the report!
