### ISSUE TITLE
GitHub Topics is BROKEN - Nov 2019 +

### ISSUE THREAD

**Issue by SentryXSI** [github/explore#1235]
Hi there. The functionality of Topics is currently broken. 

https://github.com/topics
https://github.com/stars?filter=topics

```php
Add topics to categorize your repository and make it more discoverable.
```

The restricted search results make Topics completely useless for any practical purposes.
It is frustrating ( and broken ) now because Topics no longer works the way it says it works in the documentation.

Is it a bug ? 
Does anyone know what's going on ? 

#edit - Topics almost works as long as no more than 8 people use the same tag.
https://github.com/topics/topics-is-broken

**Comment by mhterry** [comment]
https://twitter.com/maxwellterry/status/1192812733630165000

**Comment by Fradulentus** [comment]
Здравствуйте,могли бы вы перефразировать суть вопроса.

**Comment by SentryXSI** [comment]
Looks fixed. I'm very happy. Thank you !!!!

https://github.com/topics/javascript
```
Here are 131,867 public repositories matching this topic... 
```
