### ISSUE TITLE
Devise a Workflow

### ISSUE THREAD

**Issue by Persephone-Taylor** [github/explore#1243]
By compiling data; system or software scalable across all devices and industries for segmentation.  Workflow must have b2b, b2c, and b2r capabilities with a dispatching, scheduling and social media platform.  Case studies should include economics, labor, geography, revenue for 1. three year then 2. five years (1,3,5)

**Comment by jirayutza1** [comment]
> By compiling data; system or software scalable across all devices and industries for segmentation. Workflow must have b2b, b2c, and b2r capabilities with a dispatching, scheduling and social media platform. Case studies should include economics, labor, geography, revenue for 1. three year then 2. five years (1,3,5)

**Comment by Dianne120** [comment]
#

**Comment by eman291** [comment]
> > By compiling data; system or software scalable across all devices and industries for segmentation. Workflow must have b2b, b2c, and b2r capabilities with a dispatching, scheduling and social media platform. Case studies should include economics, labor, geography, revenue for 1. three year then 2. five years (1,3,5)

**Comment by danffer2019** [comment]
通过编写数据; 系统或软件的可扩展的跨所有设备和行业进行分割。工作流必须具有b2b，b2c和b2r功能，并具有调度，调度和社交媒体平台。案例研究应包括经济学，劳动力，地理，收入1.三年，然后2.五年（1、3、5）

**Comment by danffer2019** [comment]
> 🐱
