### ISSUE TITLE
Newsletter not working!

### ISSUE THREAD

**Issue by parthd24** [github/explore#1273]
I’ve been trying to receive daily emails via the GitHub Explore newsletter but I don’t think I’ve received any 🤔. I want to make sure customers are receiving these if they've opted in!

What's wrong here? Here's a screenshot of which setting I'm on:

<img width="1034" alt="Screen Shot 2019-11-08 at 2 42 51 PM" src="https://user-images.githubusercontent.com/16566705/70096705-882f2180-15dc-11ea-82aa-d14790c01267.png">

Related: https://github.com/github/explore/issues/1272

**Comment by ayush1808** [comment]
After your report I have changed my plan to check weather it is concern of others also or of just you . After checking this we will inform you.
