### ISSUE TITLE
4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.

### ISSUE THREAD

**Issue by sintuksuman** [github/explore#1342]
4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.\

def computepay():
    hrs = input("Enter Hours:")
    h = float(hrs)
    rate = input("Enter Rate:")
    r = float(rate)
    pay = (h * r)
    if h <= 40 :
        return(pay)
    else :
        ovrhrs = (h-40)
        regular = (r*40)
        othrs = ovrhrs * (r *1.5)
        ovrpay = (regular + othrs)
        return(ovrpay)
result=computepay()
print(result)

**Comment by sintuksuman** [comment]
thsi is correct code

**Comment by wensum** [comment]
Thank you

**Comment by BaseMax** [comment]
This title is really long and big! Please use short and better title.
Thanks you :+1: 

Regards,
Max

**Comment by AndMe-me** [comment]
AndtoMe

**Comment by AndMe-me** [comment]
READ!ME!Read&​ME!Read!ME

**Comment by AndMe-me** [comment]
READ!ME!Read&​ME!Read!ME

**Comment by AndMe-me** [comment]
@AndMe-me

**Comment by AndMe-me** [comment]
@sintuksuman

**Comment by AndMe-me** [comment]
@BaseMax

**Comment by AndMe-me** [comment]
@bruce

**Comment by AndMe-me** [comment]
@ @wensum

**Comment by AndMe-me** [comment]
@AndMe-me
