### ISSUE TITLE
Missing topic?

### ISSUE THREAD

**Issue by LimpingNinja** [github/explore#1452]
Came into this repository from: https://github.com/topics/mud-server

Oddly I can’t see a topic listed there, I wanted to update the topic with relevant links.

**Comment by armican** [comment]
Github ogrencem

**Comment by R4356th** [comment]
That is because "mud-server" is not curated yet. GitHub shows custom topics when it is not curated.

**Comment by MikeMcQuaid** [comment]
What @R4356th said!
