### ISSUE TITLE
Clarify how a collection should be sorted

### ISSUE THREAD

**Issue by tobiasvl** [github/explore#1469]
I want to propose adding an item to a collection, but I'm not sure where in the list to add it.

Is it already sorted by some criterion, like the number of stars? Or should I add the item to the bottom? Does it depend on the collection?

It would be nice if this were clarified.

**Comment by mekmin100** [comment]
github sayfamda tam salayıcı sanırım gizli ve meşakatli biri bana yardım ederse sevinirim koleksiyonumu ve tam donanımda çalışma alanımı istiyorum ve ben ressam tasarımcı müzisyen bir sanatcıyım ve yetenekli bir yaratıcı bilim adamıyım yani farklı biriyim ve yazım gibi ilgiç biriyim nerde ne yazıcahım hiç önemli deyil bilgisayarım duşuk model ust model olsaydı artı böyle sorunlar yaşamazdım teşekürler

**Comment by MikeMcQuaid** [comment]
Generally it's worth just adding to the bottom. There is no sorting done currently.
