### ISSUE TITLE
Ownership Request: Explore Team

### ISSUE THREAD

**Issue by mms710** [github/explore#1473]
We're doing the first round of follow-ups based on research that a group of senior and staff engineers did on ownership for items in the service catalog. We want to suggest/ask if your team is willing to own the following items and has the staffing to do so. It's possible that this question might arise just due to out of date documentation and you already do own these items, but we want to make sure to check in and get your team's explicit approval or disapproval because we want to make sure there's no surprises as part of this process. If you do agree to own these items, we would ask that your team updates the ownership.yaml file referenced in the service catalog to show your ownership. As a note, this is just the first round of research on the items the team felt were most critical, and we expect to do one more round once we've done a more thorough review of the remaining items.

**Requests**:

- [ ] Review the list of below services and either accept or reject ownership for them. If you don't think you are the right owner for something, please let us know if you have any ideas of who might be the correct team.
- [ ] For any services you accept, please link issues or PRs to this issue to update the service catalog for these items so we can have up to date records as we continue on our ownership research

**Due Dates**:
We would ideally like to have an answer on this and a PR to fix the underlying documentation by May 15th. However, this is a short timeline so please feel free to push back if that won't work for the team.

**List of Services**:
- https://catalog.githubapp.com/services/explore-feed/slos
- https://catalog.githubapp.com/services/marketing-crons/slos

(cc @derekprior )

**Comment by derekprior** [comment]
@kenyonj I feel like you and I had talked about explore-feed in the past and you mentioned that it was unused? Should I retire it from the service catalog?

I don't know what Marketing Crons is, but the name strikes me as being more closely related to @github/site-engineering cc @talsafran for thoughts?

**Comment by kenyonj** [comment]
> @kenyonj I feel like you and I had talked about explore-feed in the past and you mentioned that it was unused? Should I retire it from the service catalog?

That’s correct @derekprior. explore-feed is not used anywhere and was just an experiment.

**Comment by talsafran** [comment]
👋 I think marketing-crons can be retired too... happy to take over ownership and retire it.

**Comment by mms710** [comment]
@talsafran would you be willing to open a PR and link it to this issue for your team to take on ownership of marketing-crons and retire it?

@derekprior would it make sense for your team to take on explore-feed and retire it, or should that also live with site-engineering?

**Comment by talsafran** [comment]
@mms710 can happily do that.

So, I probably should've asked this yesterday 😊:

- To update ownership, do you mean just update repo's `ownership.yaml` file? Or is there another source of truth?

- What's involved in retiring a service exactly? Is there a playbook? I couldn't find any documentation, would love a nudge in the right direction 🙃

**Comment by derekprior** [comment]
It makes sense for us to take explore-feed. @kenyonj - are you able to grant me access to the `github/explore-feed` repo?

**Comment by derekprior** [comment]
> What's involved in retiring a service exactly? Is there a playbook? I couldn't find any documentation, would love a nudge in the right direction 🙃

I'm trying to figure this out too! In the case of explore-feed, it seems like the moda app is alredy deprovisioned, so I think I just need to remove the ownership information from the repo?

**Comment by kenyonj** [comment]
> It makes sense for us to take explore-feed. @kenyonj - are you able to grant me access to the `github/explore-feed` repo?

Just added @github/explore as admins on the github/explore-feed repo

**Comment by mms710** [comment]
@talsafran Thanks for asking! You are absolutely correct that the next step to officially "claim" the service is to update the `ownership.yaml` file for the service.

@derekprior is absolutely right that we don't have a playbook for how to sunset a service (yet!). I'd recommend working with your product counterparts first to determine if any customer communications are needed before you sunset the service, then tackling the engineering portion.

**Comment by Resnimi** [comment]
> @mms710 can happily do that.
> 
> So, I probably should've asked this yesterday 😊:
> 
> * To update ownership, do you mean just update repo's `ownership.yaml` file? Or is there another source of truth?
> * What's involved in retiring a service exactly? Is there a playbook? I couldn't find any documentation, would love a nudge in the right direction 🙃

![image](https://user-images.githubusercontent.com/7670114/87450132-60b12600-c5bb-11ea-85f7-b8c9d80a9795.png), @talsafran! I'm helping to track file maintainership. Have you opened or merged a PR to sunset this file yet: https://catalog.githubapp.com/services/marketing-crons/slos? If so, would you mind pointing me to the relevant PR?

If not, please just let me know when your team may have time to sunset this file? Thank you kindly for your help!

**Comment by talsafran** [comment]
@Resnimi I updated https://github.com/github/marketing-crons with an `ownership.yaml` file. What needs to be done in order to sunset this repo?

**Comment by mms710** [comment]
@talsafran if this repo is no longer in use, you can just archive it and it'll be removed from the service catalog automatically within a few hours.

**Comment by talsafran** [comment]
@mms710 cool, it's archived and not showing up in the catalog anymore: https://catalog.githubapp.com/services/marketing-crons

**Comment by Resnimi** [comment]
> @mms710 cool, it's archived and not showing up in the catalog anymore: https://catalog.githubapp.com/services/marketing-crons

You rock, thank you so much, @talsafran!!

**Comment by mms710** [comment]
@talsafran if the `ownership.yaml` file in explore-feeds repo is up to date, you can close this issue as done!

**Comment by talsafran** [comment]
The https://github.com/github/explore-feed repo was never running on any special infrastructure from what I remember (just Jekyll + GitHub Pages), and _I believe_ never made it to production. 

In any case, I created an [`ownership.yaml`](https://github.com/github/explore-feed/blob/master/ownership.yaml) for the @github/explore team. @kenyonj can you confirm that that service is no longer being used, and if so then [archive the repo](https://github.com/github/explore-feed/settings#danger-zone)?

**Comment by mms710** [comment]
omg I love cleanup! 🤞 for it not being in prod anymore!

**Comment by kenyonj** [comment]
> In any case, I created an [`ownership.yaml`](https://github.com/github/explore-feed/blob/master/ownership.yaml) for the @github/explore team. @kenyonj can you confirm that that service is no longer being used, and if so then [archive the repo](https://github.com/github/explore-feed/settings#danger-zone)?

Confirmed that this is no longer used, other than recent testing for something completely unrelated. I'll go ahead and follow the archive process. Thanks @talsafran !

**Comment by talsafran** [comment]
🏆
