### ISSUE TITLE
çalışma alanı arıyorum

### ISSUE THREAD

**Issue by mekmin100** [github/explore#1482]
bana birileri git hub sayfalarını youtube gibi canlı sonuçlar gibi salıya bilirmi ben bunu arıyorum

**Comment by armican** [comment]
Aynen ogrenmek istiyiyorum calişmak kazanmak kazandirmak istiyorum

**Comment by mekmin100** [comment]
evet yapabileceyim bir şeyler varsa bende çalışmak isterim beni yönlendiricek bir çalışma alanı olursa bende yetenekli biriyim bunu kanıtlarım ve tabiki bilgisyar yöntemleriyle ve sayfamı arıyorum teşekürler
