### ISSUE TITLE
JASA KONTRAKTOR JEMBER, HP/WA 0822-5760-0433

### ISSUE THREAD

**Issue by terasindojember** [github/explore#1535]
![Slide11](https://user-images.githubusercontent.com/66876099/84571629-a1e8c700-adbe-11ea-9009-cc5584457db8.JPG)
Cakupan kerja jasa kontraktor
Pengerjaan suatu proyek baik berskala kecil maupun besar tentu memerlukan jasa kontraktor. Jasa kontraktor sendiri dapat diartikan sebagai orang atau badan usaha berbadan hukum yang dikontrak oleh kline guna menggarap proyeknya. Dasar yang digunakan oleh kedua belah pihak dalam mengerjakan proyek ini adalah surat perjanjian kontrak kerja (spk).

 

Klien memang lebih nyaman menggunakan jasa dari kontraktor terutama untuk menangani proyek besar. Seperti proses pembangunan real estate, gedung perkantoran, mall dan pusat perbelanjaan. Terdapat beberapa alasan yang melatar belakangi keputusan kebanyakan klien untuk menangani proyeknya.

 

Alasan utamanya adalah karena jasa kontraktor berbadan hukum sehingga memiliki sertifikat dan lisensi resmi. Bukan hanya sekedar menangani proyek berskala besar, kontraktor juga bersedia mengerjakan proyek berskala kecil semisal pembangunan rumah. Sebelum proses ini dimulai, kontraktor akan melakukan beberapa diskusi dengan klien.

 

Aspek yang dibahas dalam pertemuan ini adalah Rencana Anggaran Biaya (RAB), surat perjanjian kontrak kerja dan waktu survei lokasi. Pada saat melakukan survei, pihak kontraktor pun akan melakukan pengukuran lebih detail. Tujuannya adalah agar pembuatan RAB menjadi lebih akurat.

 

Pembiayaan jasa kontraktor
Sistem pembayaran cost and fee
Dalam penerapan sistem pembayaran cost and fee biasanya posisi pihak kontraktor adalah sebagai pengelola. Kondisi ini tentu berbeda dengan sistem pembayaran termin dimana penggunaan sistem ini memberikan kesempatan kepada kontraktor untuk mengambil untung. Persentase keuntungan yang menjadi milik kontraktor adalah 10% dari total nilai pengerjaan proyek.

 

Sebelum melakukan kesepakatan dengan klien, kontraktor wajib menyiapkan anggara serta jadwal pembayaran proyek. Perencanaan ini bertujuan guna memudahkan klien dalam mengetahui total nominal yang harus dibayarkan beserta waktunya. Melalui penggunaan sistem ini, maka nominal pembayaran dari klien kepada jasa kontraktor Jember berbeda-beda setiap bulannya.

 

Perbedaan pembayaran per bulan tersebut tentu didasarkan pada capaian pengerjaan proyek yang sedang digarap kontraktor. Akan tetapi, Anda tidak perlu khawatir karena bisa memperkirakan berapa uang yang harus dibayarkan setiap bulannya. Ini disebabkan pihak kontraktor telah merinci anggaran proyek per bulan.

 

Sistem pembayaran termin
Anda harus melakukan pembayaran sebanyak empat tahap apabila kontraktor menggunakan sistem termin. Jumlah nominal yang Anda bayarkan tersebut pada setiap periodenya tentu didasarkan atas capaian pengerjaan proyek. Selain itu, sebelum penggarapan proyek dimulai, pihak kontraktor biasanya meminta Anda membayarkan uang muka atau Down Payment (DP).

 

Umumnya, jumlah uang DP yang harus Anda bayarkan adalah 30% dari kesepakatan nilai kontrak.

Setelah pembayaran uang muka selesai, maka penyedia jasa kontraktor akan segera memulai proses pengerjaan proyek. Ketika pengerjaan proyek sudah mencapai 50%, maka Anda kembali diminta membayarkan angsuran termin kedua.

 

Begitu juga pembayaran termin berikutnya harus Anda sesuaikan dengan apa yang telah disepakati bersama kontraktor. Barulah ketika proyek selesai, Anda bisa melunasi kekurangan dari total pembiayaan. 

 

Cara pemesanan jasa kontraktor Jember 
Jasa kontraktor Kami memang berdomisili di kota Jember. Pemilihan jasa kontraktor memang harus Anda lakukan secara selektif. Kami tidak hanya bersedia untuk melayani pengerjaan proyek di daerah Jember melainkan di daerah Jawa Timur lainnya bahkan seluruh Indonesia. 

[HUBUNGI KAMI](https://api.whatsapp.com/send?phone=6282257600433)

HP/WA 0822-5760-0433

**Comment by matd34566** [comment]
Duplicate of #
