### ISSUE TITLE
Place to report bugs and feature requests for GitHub?

### ISSUE THREAD

**Issue by trusktr** [github/explore#1536]
Unless I missed it, there doesn't seem to be something like a https://github.com/github/github repo, that even without source code could serve as a place for feature discussion and bugs.

It would be totally helpful to have that, to get more involvement from the community in directing the future of GitHub features (and helping for bugs to be found more easily).

This repo seems like the closest thing to that, so that's why I chose to open this here.

**Comment by trusktr** [comment]
Before someone replies with an email address for such things, I am aware that we can send emails to GitHub, but this does not include the level of public interactivity that a GitHub repo has.

I'm writing this to ask if GitHub may be interested in a public repo that the community can use as an official place for issues.

Maybe even other features like Wiki and Projects could be useful for the community.

The Projects feature could be a way to show the public what the roadmap is, and to allow them to _more easily_ (than with emails) help guide the future of GitHub in a collaborative way.

With email only, people can not see discussions publicly, and can not join them unless someone else CC's them to it; this sort of thing still holds it place and has usefulness for certain private discussion, but it does not get the GitHub community involved in GitHub itself in the same way that people get involved with the many open-source projects on GitHub.

Is this something GitHub would be willing to enable? Or does it already exist and I missed it?

**Comment by trusktr** [comment]
Trying to report a GitHub bug is, ironically, a lot more difficult (and thus less likely) than with any other project on GitHub.

**Comment by trusktr** [comment]
Repos like the following exist, but they aren't official (I haven't checked to see if any GitHub employees actually respond there): https://github.com/isaacs/github

**Comment by ChillerDragon** [comment]
BTW there is https://support.github.com/contact/feedback but yea a public issue system would be nice

**Comment by Kybaush-alt** [comment]
People in my particular situation may find it hard to get a proper answer.

**Comment by trusktr** [comment]
Ooooh, looks like there is a new official GitHub forum: https://github.community (powered by Discourse). This might be the best place now.

**Comment by Jme7** [comment]
Thanks for this!

**Comment by MikeMcQuaid** [comment]
Closing this as you've figured out the best places @trusktr 😁.

**Comment by Jme7** [comment]
Ok
