### ISSUE TITLE
collections should be sorted by number of stars

### ISSUE THREAD

**Issue by ssbarnea** [github/explore#1653]
Some collections are sorted in order of entry addition, some collections are sorted alphabetically. Still none of this is a correct/fair/unbiased way to advertise the projects inside them as it would advantage either the time when it was entered or the first letters from the alphabet.

One less biases way to display entries is based on the number of stars these projects have, something that is already working well for **topics**.

We need the same for collections, as nobody expects to keep sorting order manually updated.

I am afraid that this change request requires some server-side changes on the way collections are displayed.

**Comment by MikeMcQuaid** [comment]
Nice idea but we have no plans to implement this currently.

**Comment by ssbarnea** [comment]
So there are no plans to address the biased approach, which advantages those that were added first? This means that even a 5 stared listing that may be unmaintained will have better visibility than >1000 star one? 🤔

**Comment by MikeMcQuaid** [comment]
Yes. Stars are not the sole measure of popularity.
