### ISSUE TITLE
BSCN Bonsaicoin

### ISSUE THREAD

**Issue by Bizzcoin** [github/explore#1709]
`
{
  "senderPublicKey": "CBuZkP9Q5SiCDQ8VQCuyQnmFodThAx3eb8HerDHXABm6",
  "quantity": "2100000000000000",
  "fee": 100000000,
  "description": "",
  "type": 3,
  "version": 2,
  "reissuable": true,
  "script": null,
  "sender": "3P8VfT7Z9zjb5X3UpZ1DSG37pUJSUn9NLab",
  "feeAssetId": null,
  "chainId": 87,
  "proofs": [
    "3tmXRsfxf57mJkRiXRPjuqnNreF5bPCuTFbyDwdyXMERZ1wPKsRCcvW6UsKe5xXc2oHz7wnhHiugQeeJS1Ra1hg3"
  ],
  "assetId": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe",
  "decimals": 8,
  "name": "Bonsai Coin",
  "id": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe",
  "timestamp": 1598240300319,
  "height": 2209660
}`

**Comment by atena5101** [comment]
Ok

**Comment by atena5101** [comment]
Ok

**Comment by Bizzcoin** [comment]
> ` { "senderPublicKey": "CBuZkP9Q5SiCDQ8VQCuyQnmFodThAx3eb8HerDHXABm6", "quantity": "2100000000000000", "fee": 100000000, "description": "", "type": 3, "version": 2, "reissuable": true, "script": null, "sender": "3P8VfT7Z9zjb5X3UpZ1DSG37pUJSUn9NLab", "feeAssetId": null, "chainId": 87, "proofs": [ "3tmXRsfxf57mJkRiXRPjuqnNreF5bPCuTFbyDwdyXMERZ1wPKsRCcvW6UsKe5xXc2oHz7wnhHiugQeeJS1Ra1hg3" ], "assetId": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe", "decimals": 8, "name": "Bonsai Coin", "id": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe", "timestamp": 1598240300319, "height": 2209660 }`

**Comment by atena5101** [comment]
#1709

**Comment by Bizzcoin** [comment]
{
  "senderPublicKey": "CBuZkP9Q5SiCDQ8VQCuyQnmFodThAx3eb8HerDHXABm6",
  "quantity": "2100000000000000",
  "fee": 100000000,
  "description": "",
  "type": 3,
  "version": 2,
  "reissuable": true,
  "script": null,
  "sender": "3P8VfT7Z9zjb5X3UpZ1DSG37pUJSUn9NLab",
  "feeAssetId": null,
  "chainId": 87,
  "proofs": [
    "3tmXRsfxf57mJkRiXRPjuqnNreF5bPCuTFbyDwdyXMERZ1wPKsRCcvW6UsKe5xXc2oHz7wnhHiugQeeJS1Ra1hg3"
  ],
  "assetId": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe",
  "decimals": 8,
  "name": "Bonsai Coin",
  "id": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe",
  "timestamp": 1598240300319,
  "height": 2209660
}

**Comment by atena5101** [comment]
> ` { "senderPublicKey": "CBuZkP9Q5SiCDQ8VQCuyQnmFodThAx3eb8HerDHXABm6", "quantity": "2100000000000000", "fee": 100000000, "description": "", "type": 3, "version": 2, "reissuable": true, "script": null, "sender": "3P8VfT7Z9zjb5X3UpZ1DSG37pUJSUn9NLab", "feeAssetId": null, "chainId": 87, "proofs": [ "3tmXRsfxf57mJkRiXRPjuqnNreF5bPCuTFbyDwdyXMERZ1wPKsRCcvW6UsKe5xXc2oHz7wnhHiugQeeJS1Ra1hg3" ], "assetId": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe", "decimals": 8, "name": "Bonsai Coin", "id": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe", "timestamp": 1598240300319, "height": 2209660 }`
 # 1709

**Comment by Bizzcoin** [comment]
> ` { "senderPublicKey": "CBuZkP9Q5SiCDQ8VQCuyQnmFodThAx3eb8HerDHXABm6", "quantity": "2100000000000000", "fee": 100000000, "description": "", "type": 3, "version": 2, "reissuable": true, "script": null, "sender": "3P8VfT7Z9zjb5X3UpZ1DSG37pUJSUn9NLab", "feeAssetId": null, "chainId": 87, "proofs": [ "3tmXRsfxf57mJkRiXRPjuqnNreF5bPCuTFbyDwdyXMERZ1wPKsRCcvW6UsKe5xXc2oHz7wnhHiugQeeJS1Ra1hg3" ], "assetId": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe", "decimals": 8, "name": "Bonsai Coin", "id": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe", "timestamp": 1598240300319, "height": 2209660 }`

**Comment by atena5101** [comment]
@atena5101

**Comment by atena5101** [comment]
Duplicate of #

**Comment by a0969818431** [comment]
> { "senderPublicKey": "CBuZkP9Q5SiCDQ8VQCuyQnmFodThAx3eb8HerDHXABm6", "quantity": "2100000000000000", "fee": 100000000, "description": "", "type": 3, "version": 2, "reissuable": true, "script": null, "sender": "3P8VfT7Z9zjb5X3UpZ1DSG37pUJSUn9NLab", "feeAssetId": null, "chainId": 87, "proofs": [ "3tmXRsfxf57mJkRiXRPjuqnNreF5bPCuTFbyDwdyXMERZ1wPKsRCcvW6UsKe5xXc2oHz7wnhHiugQeeJS1Ra1hg3" ], "assetId": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe", "decimals": 8, "name": "Bonsai Coin", "id": "HLmc9UeVRDWLJTcF1rJELroK7b8FWdsD6i32fPoUgPHe", "timestamp": 1598240300319, "height": 2209660 }

**Comment by atena5101** [comment]
در تاریخ پنجشنبه ۲۷ اوت ۲۰۲۰،‏ ۱:۱۲ a0969818431 <notifications@github.com>
نوشت:
