### ISSUE TITLE
Profile Readme Section for organisations

### ISSUE THREAD

**Issue by darshan-jain** [github/explore#1799]
Have you ever come across an organisation and you have no clue what the organisation does?
Well, don’t worry you are not the only one stuck there. Github had launched an option for users to greet profile visitors with some insights about the repo owner. I genuinely think this can be highly useful for open source repositories of organisations so that it would provide good insight about the entire repo and what sort of open source contribution they would like to see.

**Comment by deniseyu** [comment]
Hi @darshan-jain I'm not sure if you intended to post this suggestion here - thanks for the product feedback anyway 😄  Closing this out as it's not directly related to Explore.
