### ISSUE TITLE
Collections have arbitrary sorting

### ISSUE THREAD

**Issue by mit-mit** [github/explore#1889]
The collections available at https://github.com/collections seem to have a fairly arbitrary sorting, relying on the order in which they are listed in the source MD file.

One concrete example is https://github.com/collections/programming-languages -- the languages here are listed in a very arbitrary order, which has no connections to common metrics such as programming language usage.

I suggest that collections (when rendered to HTML) are sorted by some metrics, for example GitHub Stars or Forks.

**Comment by walid161hatam** [comment]
BTC send

**Comment by kenyonj** [comment]
> relying on the order in which they are listed in the source MD file.

That is correct, we do not support dynamic ordering currently.

**Comment by mit-mit** [comment]
@kenyonj why did you close this? This is a request to change that behavior, which frankly makes no sense.

**Comment by kenyonj** [comment]
> @kenyonj why did you close this? This is a request to change that behavior, which frankly makes no sense.

This repository is meant for the curation of the data that lives on github.com/topics and github.com/collections. Please feel free top open a discussion on https://github.com/github/feedback to discuss further. Thank you!
