### ISSUE TITLE
Could we add GridSound into the Music collection?

### ISSUE THREAD

**Issue by Mr21** [github/explore#282]
Hi :)

Since two years we have started a DAW (digital audio workstation) written in JS by using the new WebAudio API. We think our project could be a good fit to this collection, our app is directly usable on GitHub page at https://gridsound.github.io/daw.

(If you are agree i could make a PR for you)

Thanks for your attention

**Comment by talsafran** [comment]
Hi @Mr21 thanks for the contribution ❤️. Very cool project!

Unfortunately, as per our [contribution guidelines](https://github.com/github/explore/blob/master/CONTRIBUTING.md#guidelines), we don't allow self promotion if you are a maintainer of the project:

> Unaffiliated with the project (not self-promoting as e.g. a maintainer, creator, contractor or employee)

Thank you!

**Comment by Mr21** [comment]
i see, thank you
