### ISSUE TITLE
Increase (or remove) limit on collection items

### ISSUE THREAD

**Issue by brandonrosage** [github/explore#288]
[A recent PR](https://github.com/github/explore/pull/286) that adds an item to the "Programming Languages" collection [pushes the total number of items there past 40 -- the limit](https://travis-ci.org/github/explore/builds/396134294?utm_source=github_status&utm_medium=notification). It'd be nice to consider removing the limit, or increasing it to 100.

**Comment by rawit1976** [comment]
Good

**Comment by istina2018** [comment]
The power of love 2018!

**Comment by Alexkho82** [comment]
#288

**Comment by Alexkho82** [comment]
#288
