### ISSUE TITLE
Optimizing images automatically

### ISSUE THREAD

**Issue by abranhe** [github/explore#432]
New feature: [**Optimizing images automatically**](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/).

I have seen most of the pull request fail because of large images. Topic images should not exceed 75000 bytes *https://travis-ci.org/github/explore/builds/445250712*, so why not to include [ImgBot](https://github.com/marketplace/imgbot)? 

ImgBot will crawl through all the images files and losslessly compress them. This will make the file size go down, but leave the dimensions and quality untouched.

This should be great because the size of the repository will notoriously go down.
Example of this: https://github.com/abranhe/explore/pull/1/files

[<img width="1197" alt="screen shot 2018-10-25 at 9 35 10 am" src="https://user-images.githubusercontent.com/21347264/47504117-96d3d280-d839-11e8-9ad0-748104b018b3.png">](https://github.com/abranhe/explore/pull/1/files)

**Comment by MikeMcQuaid** [comment]
Reducing the file size would be good but we still require the images to be certain dimensions so I'm not convinced this would save much work. Is there anything that will also fix the dimensions?

**Comment by abranhe** [comment]
> Is there anything that will also fix the dimensions?

No, I don't think **ImgBot** would fix the dimensions, it will keep the dimensions untouched, but still there are many other PRs that are submitted with a correct image dimension (288x288) but still with a large size (over 7.5 kb). 

I don't think **ImgBot**  would do anything else other than reduce a little bit the images size, so it's up to you guys if you want to integrate it to the repo. **THIS IS ONLY A RECOMENDATION!**

**Comment by tranghoangcz77** [comment]
Bình chọn khi có vấn đề gì thì làm lai cho chuẩn mực  , và lợi ích chung cho tất cả xã hội chúng ta đặt lên hàng đầu .

**Comment by MikeMcQuaid** [comment]
Thanks @abranhe! Passing for now.
