### ISSUE TITLE
public static final Dialog yesNoDialog(Context context, String message, DialogInterface.OnClickListener yesAction, DialogInterface.OnClickListener noAction) { AlertDialog.Builder builder = new AlertDialog.Builder(context,R.style.todoDialogLight); builder.setTitle(context.getString(R.string.app_name)) .setMessage(message) .setCancelable(false) . etPositiveButton("YES", yesAction) .setNegativeButton ("NO", noAction); return builder.create(); }

### ISSUE THREAD

**Issue by randyc1975** [github/explore#470]
public static final Dialog yesNoDialog(Context context, String message, DialogInterface.OnClickListener yesAction, DialogInterface.OnClickListener noAction) { AlertDialog.Builder builder = new AlertDialog.Builder(context,R.style.todoDialogLight); builder.setTitle(context.getString(R.string.app_name)) .setMessage(message) .setCancelable(false) .
etPositiveButton("YES", yesAction) .setNegativeButton
("NO", noAction); return builder.create(); }

**Comment by pedokiller696** [comment]
Headache
