### ISSUE TITLE
Sort by stars

### ISSUE THREAD

**Issue by cormullion** [github/explore#479]
It might be a good idea to sort the [list of languages](https://github.com/github/explore/blob/master/collections/programming-languages/index.md) by the number of stars, rather than the current order (whatever that might be).

At the time of writing, this list would be as follows:

|Language|Description                       |Stars                             |Forks                             |
|--- |--- |--- |--- |
|golang / go|The Go programming language        |50232 |6921  |
|apple / swift|The Swift Programming Language     |45946 |7301  |
|Microsoft / TypeScript|TypeScript is a superset of JavaScript that compiles to clean JavaScript output.|42033 |6020  |
|rust-lang / rust|A safe, concurrent, practical language.|32262 |5350  |
|JetBrains / kotlin|The Kotlin Programming Language    |25483 |2946  |
|python / cpython|The Python programming language    |21193 |7862  |
|php / php-src|The PHP Interpreter                |20740 |5112  |
|JuliaLang / julia|The Julia Language: A fresh approach to technical computing.|18936 |3085  |
|ruby / ruby|The Ruby Programming Language      |15099 |4064  |
|jashkenas / coffeescript|Unfancy JavaScript                 |14989 |1991  |
|elixir-lang / elixir|Elixir is a dynamic, functional language designed for building scalable and maintainable applications|14312 |2074  |
|crystal-lang / crystal|The Crystal Programming Language   |12301 |954   |
|PowerShell / PowerShell|PowerShell for every system!       |11883 |1904  |
|scala / scala|The Scala programming language     |10987 |2597  |
|dotnet / roslyn|The Roslyn .NET compiler provides C# and Visual Basic languages with rich code analysis APIs.|10438 |2481  |
|clojure / clojure|The Clojure programming language   |7493  |1212  |
|micropython / micropython|MicroPython - a lean and efficient Python implementation for microcontrollers and constrained systems|7484  |2119  |
|erlang / otp|Erlang/OTP                         |7256  |1923  |
|nim-lang / Nim|Nim is a compiled, garbage-collected systems programming language with a design that focuses on efficiency, expressiveness, and elegance (in that order of priority).|6179  |767   |
|purescript / purescript|A strongly-typed language that compiles to Javascript|5330  |400   |
|elm / compiler|Compiler for Elm, a functional language for reliable webapps.|4902  |389   |
|dotnet / csharplang|The official repo for the design of the C# programming language|3732  |383   |
|red / red|Red is a next-generation programming language strongly inspired by Rebol, but with a broader field of usage thanks to its native-code compiler, from system programming to high-level scripting and c…|3527  |346   |
|ponylang / ponyc|🐴 Pony is an open-source, actor-model, capabilities-secure, high performance programming language|3515  |304   |
|Frege / frege|Frege is a Haskell for the JVM. It brings purely functional programing to the Java platform.|3122  |131   |
|racket / racket|The Racket repository              |2685  |431   |
|idris-lang / Idris-dev|A Dependently Typed Functional Programming Language|2644  |593   |
|ocaml / ocaml|The core OCaml system: compilers, runtime system, base libraries|2120  |499   |
|typelead / eta|The Eta Programming Language, a dialect of Haskell on the JVM|2094  |139   |
|nulang / nu|Nu is an interpreted Lisp that builds on the Objective-C runtime and Foundation framework.|2023  |246   |
|gkz / LiveScript|LiveScript is a language which compiles to JavaScript. It has a straightforward mapping to JavaScript and allows you to write expressive code devoid of repetitive boilerplate. While LiveScript adds…|2009  |158   |
|IoLanguage / io|Io programming language. Inspired by Self, Smalltalk and LISP.|1969  |257   |
|dlang / dmd|dmd D Programming Language compiler|1865  |480   |
|zdevito / terra|Terra is a low-level system programming language that is embedded in and meta-programmed by the Lua programming language.|1792  |143   |
|Microsoft / visualfsharp|The Visual F# compiler, FSharp.Core library, and tools for F#|1462  |393   |
|FascinatedBox / lily|This repository has moved: https://gitlab.com/FascinatedBox/lily|1072  |43    |
|rakudo / rakudo|🦋 Rakudo Perl 6 – Perl 6 on MoarVM and the JVM|1044  |316   |
|chapel-lang / chapel|a Productive Parallel Programming Language|734   |195   |
|lucee / Lucee|Lucee Server is a dynamic, Java based (JSR-223), tag and scripting language used for rapid web application development. Lucee simplifies technologies like webservices (REST, SOAP, HTTP), ORM (Hiber…|407   |78    |
|eclipse / golo-lang|Golo - a lightweight dynamic language for the JVM.|380   |92    |
|gosu-lang / gosu-lang|The Gosu programming language      |272   |58    |

**Comment by StefanKarpinski** [comment]
Spitballing, collective repo stars distributed over languages as detected would make sense, no?

**Comment by MikeMcQuaid** [comment]
@cormullion This is a good idea. Are you thinking of manually reordering them or that this should be done automatically?

**Comment by cormullion** [comment]
Hi Mike. I was thinking of making a quick manual edit/PR as an interim thing. But ideally and eventually the page would obtain the stars and network data—and sort the results—automagically. (And I wouldn’t know how to do that... 😀)

**Comment by MikeMcQuaid** [comment]
👍 to a manual PR for now, that'd be great!

**Comment by ylluminate** [comment]
Looks like the list is out of date again... I'm wondering if perhaps - to be more fair - we should maybe sort this list alphabetically as well vs by star?

**Comment by MikeMcQuaid** [comment]
The list will continue to become outdated until there's something automated to address that or a CI check. We'll review PRs for either. We should sort by stars rather than alphabetically as stars demonstrate community interest.
