### ISSUE TITLE
New part

### ISSUE THREAD

**Issue by lisabufzinski1671** [github/explore#493]
They are connected to my PayPal account

**Comment by lisabufzinski1671** [comment]
I have money tide in so I can't close it

**Comment by lisabufzinski1671** [comment]
I can't do anything about it. I will be penalized if I follow though with
anything else. I'm sorry that I bother you with my problem and I will have
to deal with it I'm already getting reprecusioms so please everything will
be ok thank you all sorry again for bothering you


Lisa Budzinski

**Comment by shaski** [comment]
loveandGravitY
