### ISSUE TITLE
Copy error about Campus Experts in /explore

### ISSUE THREAD

**Issue by mozzadrella** [github/explore#502]
![screenshot 2018-12-20 10 04 23](https://user-images.githubusercontent.com/1874003/50292395-fec02700-043e-11e9-8d84-1ac22cde9696.png)

Copy is the same as the open source guides (which I tried to find to send a PR in this repo, but could not discover :/) 

Should read: 

## Join GitHub Campus Experts
Apply to join the training and become a Campus Expert.

- Learn community leadership skills
- Get hands-on mentorship and advice
- Get access to exclusive opportunities

Merci!

**Comment by indovideograpy** [comment]
Pada tanggal Kam, 20 Des 2018 22.10 Vanessa <notifications@github.com
menulis:

**Comment by Suz1118** [comment]
Oh my, I'm not sure I qualify to help on any of these products/projects.  However, I am willing learn from the ground up, possibly in this case, the basement up.  With that said, please feel free to assign me any type of grunt work and I will be greatful and appreciative.  Thank you all for this opportunity.  Suz1118

**Comment by skyemorgan0907** [comment]
change from us to me

**Comment by shaun37blaze** [comment]
Someone needs to help my ignorant technology stumbling Irish ass, I'm always hacked an says my x is using all my accounts still here I'm just fucked

**Comment by bobcat87** [comment]
Please come to my face and say that. Please please please

**Comment by Kosaas** [comment]
Aún no e podido transaccionar y tengo saldo en cuenta

**Comment by MikeMcQuaid** [comment]
@mozzadrella This pubic repository is just for the open-source explore content. Please create this on a private GitHub organisation repository. Thanks!
