### ISSUE TITLE
request to be featured topic

### ISSUE THREAD

**Issue by mr-c** [github/explore#504]
Hello,

Could [`cwl`](https://github.com/topics/cwl) be a [featured topic](https://github.com/topics)?

There are more projects tagged `cwl` than 5 of the existing featured topics: 
https://github.com/topics/mvvmcross (61)
https://github.com/topics/wordplate (12)
https://github.com/topics/spacevim (34)
https://github.com/topics/reactiveui (48)
https://github.com/topics/ratchet (53)

Thanks (and apologies if this isn't the correct way to request this).

**Comment by fujisawakazuhiro** [comment]
Thanks (and apologies if this isn't the correct way to request this).

**Comment by jillmarie350** [comment]
No matter how you explain what your wanting. It should just take you there

**Comment by MikeMcQuaid** [comment]
Thanks @mr-c but we're not taking featured topics requests through this repository. Please contact support@github.com for that.
