### ISSUE TITLE
Inline Translations

### ISSUE THREAD

**Issue by ParityError** [github/explore#516]
The frequency in which repos displayed in other languages are clearly increasing, and it's somewhat frustrating to copy/paste the text into a translator every few minutes. My thinking here is why not just include inline translations for repos that are displayed in a language that isn't set to the users default?

![50](https://user-images.githubusercontent.com/36368048/50926454-44568b00-1412-11e9-88b4-6f101a834762.png)

Above you can see that on a typical day that almost 50% of the displayed trending repos in the main listing are in Chinese. **An inline translation is really needed!**

**Comment by MikeMcQuaid** [comment]
This repository is not the correct place for GitHub feature requests. Please email support@github.com.
