### ISSUE TITLE
renaming a repository causes auto builds to fail

### ISSUE THREAD

**Issue by spdegabrielle** [github/explore#536]
If a repository listed in https://github.com/github/explore/blob/master/collections/programming-languages/index.md is renamed, GitHub/explore fails builds e.g. build failure for pull request #534 .

>   1) Failure:
> collections::programming-languages collection#test_0007_fails if a user, organization, or repository has been renamed [/home/travis/build/github/explore/test/collections_test.rb:90]:
> Expected ["programming-languages: txlyre/loli has been renamed to loli-foundation/loli"] to be empty.

This can be fixed by fixing the failing reference. I have included this in pull request #535 because I was trying to resolve the build failure.

I'd suggest a possible solution is to 
a) remove renamed repository references automatically from collections/[collection name]/index.md files
b) include renaming in the repository settings 'Danger Zone' with a warning that renaming will remove the repository from any collections 

Kind regards, 
Stephen

**Comment by MikeMcQuaid** [comment]
This is intentional, thanks.

**Comment by james81787** [comment]
?
