### ISSUE TITLE
https://github.com/github/explore/issues/588#issuecomment-466796720

### ISSUE THREAD

**Issue by cmayes813** [github/explore#602]
https://github.com/github/explore/issues/588#issuecomment-466796720

**Comment by Ekkarat304** [comment]
Thank you

**Comment by Ekkarat304** [comment]
Good

**Comment by suker333** [comment]
![BTC_accepted_here reverse_L](https://user-images.githubusercontent.com/48681906/54546904-f4adb600-49a4-11e9-8019-91c25c8508f7.png)

**Comment by Rixi2203** [comment]
https://github.com/github/explore/issues/602#issuecomment-473997427
