### ISSUE TITLE
Starred repos show both star and unstar button

### ISSUE THREAD

**Issue by akmittal** [github/explore#653]
when on https://github.com/collections/front-end-javascript-frameworks page it shows both Star and Unstar button for starred Repositories.
![image](https://user-images.githubusercontent.com/1594654/55131340-4217e900-5144-11e9-8f2c-4a1ff245aa18.png)

**Comment by talsafran** [comment]
Thank you for reporting this @akmittal! You rock ✨ 

I wasn't able to reproducer the issue on my machine unfortunately. To help us figure this out, could you include your browser, operating system, and anything else that might be helpful? E.g. is JavaScript disabled, do you have any browser extensions that may be interfering, etc? Thank you!

cc @shaun81w if you were also seeing this.

**Comment by akmittal** [comment]
Hi,

**OS**: Mac OS 10.14.4
**Browser**: Chrome 73.0.3683.86, Firefox 66.0.2, Chrome Mobile 73.0.3683, Safari 12.1
**JavaScript** : Enabled

As issue is there on Mobile chrome so i dont think it has to do with extenstions. Anyway I disabled extensions and tried, issue persists.

**Comment by talsafran** [comment]
Great! We'll look into this, thank you✨ 

> As issue is there on Mobile chrome so i dont think it has to do with extenstions.

Just to confirm –– you're also seeing this issue on mobile chrome? Which operating system?

**Comment by akmittal** [comment]
> Just to confirm –– you're also seeing this issue on mobile chrome? Which operating system?

It is on Android 9.0

**Comment by badz30** [comment]
badz30@o2.pl

**Comment by shaun81w** [comment]
JavaScript is enabled no extensions I'm confused

**Comment by badz30** [comment]
Ok

**Comment by wanwanwanwanwan** [comment]
It's over to my life not support to link ,browser,chrome,google play and over it.becourse! Fake of! from persanal to give the money 
And this link email support applications in google play is to fake 
apps-help@google.com
[www.google.com](url)
, so bad and ugly.

**Comment by vnbrs** [comment]
That's also happening to me.


Google Chrome | 73.0.3683.103 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Windows 10 OS Build 17763.437
JavaScript | V8 7.3.492.27
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by shamshad95** [comment]
Hi

**Comment by shresthamanju272** [comment]
Help me to upgrade and my all kind of problem in my set

**Comment by Lubbock1972** [comment]
I don't know what I'm doing

**Comment by melvisglez** [comment]
Yo tampoco

**Comment by kenyonj** [comment]
This issue has been fixed.
