### ISSUE TITLE
Stars don't match

### ISSUE THREAD

**Issue by servusDei2018** [github/explore#767]
From https://github.com/explore -- Today at around 11:40-50 EST:
![img1](https://user-images.githubusercontent.com/37554478/58267321-61508280-7d51-11e9-9acc-1d1bb92d562f.png)

Notice that "the art of the command line" appears with **3.6k stars.**

Then...

![img2](https://user-images.githubusercontent.com/37554478/58267373-7cbb8d80-7d51-11e9-942f-8f4dc0f75807.png)

It really has **44.2k**!

**Comment by servusDei2018** [comment]
The rest of the projects that appeared in **Trending Repositories** also displayed mis-matched stars.

**Comment by kenyonj** [comment]
Thank you for bringing this to our attention!

**Comment by kenyonj** [comment]
A fix for this was just deployed. Thanks again for bringing it to our attention, @servusDei2018 !
