### ISSUE TITLE
Disable issues before launch

### ISSUE THREAD

**Issue by nayafia** [github/explore#8]
After some internal discussion, we realized we couldn't think of any great use cases for issues on this repo. The purpose of this repo is to curate and improve Topic pages, and that can all be done through PRs. So before we make the repo public, let's disable issues.

**Comment by ozbay** [comment]
Open

**Comment by talsafran** [comment]
Hi @ozbay, we recently decided to reopen Issues based on a [request](https://github.com/github/explore/pull/248#issuecomment-390380751) from a contributor. We don't see a reason not to for the time being.

Thanks!

**Comment by ozbay** [comment]
Teşekkürederim.saygılarımla
