### ISSUE TITLE
g-emoji element is invisible in good first issues of repository

### ISSUE THREAD

**Issue by lc-soft** [github/explore#802]
![选区_838](https://user-images.githubusercontent.com/1730073/59594988-80132080-9127-11e9-9d34-cf8625a03b62.png)

**Comment by kenyonj** [comment]
This could be a font issue on your machine, @lc-soft . Or, something we are doing wrong on the implementation. Can you confirm that the emoji works on the github.com/parcel-bundler/parcel/issues page?

I am seeing it correctly on my machine. Currently using Microsoft Edge Canary build 77.0.190.1.
Can you let me know what browser version/OS you are experiencing this on?

Here is a screenshot from my machine (you can see that we have different fonts based on the 📦 and 🚀 emojis in the repo description):

![Screen Shot 2019-06-17 at 2 12 42 PM](https://user-images.githubusercontent.com/4008677/59626606-50a1eb00-910a-11e9-8605-cfd6ba2335ba.png)

**Comment by lc-soft** [comment]
OS: Ubuntu 18.04.2 LTS
Browser: Chrome 70.0.3538.110

I think it's my system font problem, t's not github's problem
