### ISSUE TITLE
紧急！！！xiaofan兄弟，看到消息后麻烦你尽快跟我联系！

### ISSUE THREAD

**Issue by god1993** [github/explore#807]
联系方式：447401051@qq.com

**Comment by cyntia31** [comment]
Good

**Comment by god1993** [comment]
Please help us remove the offending code




 
---原始邮件---
发件人: "cyntia31"<notifications@github.com>
发送时间: 2019年6月21日(星期五) 凌晨1:52
收件人: "github/explore"<explore@noreply.github.com>;
抄送: "祖国的花朵"<447401051@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [github/explore] 紧急！！！xiaofan兄弟，看到消息后麻烦你尽快跟我联系！ (#807)



Good

**Comment by Romanski1** [comment]
Real Life beckround chceck

**Comment by talsafran** [comment]
HI @god1993! I've closed this PR since it doesn't seem to propose a realistic change. If you need help, please see our [contribution guidelines](https://github.com/github/explore/blob/master/CONTRIBUTING.md) for how to contribute. Thank you!
