### ISSUE TITLE
[100% Error Fixed] USB device not recognized in Windows

### ISSUE THREAD

**Issue by Asitha32** [github/explore#893]
I am using Window 10  computer and I [have](https://bigfactreview.com/how-to-fix-usb-device-not-recognized/) connected 6 USB device to each USB ports. Yesterday, When I going to connect new pen drive to another USB port, I got “USB device not recognized” error. I was confused because I didn’t get like this error [message before neither using 6 USB device at one time.](https://bigfactreview.com/how-to-fix-usb-device-not-recognized/)

So I was searching lots of solutions and I found 6 way to solve this error but Only one solution worked for me. I will mention that solution first, but also I will mention another 5 solutions as well. If first method won’t work for you, try [next 5 methods to fix this error. I am sure this error will fix with these 6 solutions.](https://bigfactreview.com/how-to-fix-usb-device-not-recognized/)

When you connected USB device to PC you will get an error massage like “ The last USB device you connected to this computer malfunctioned, and Windows does not recognize it“. This problem is not related with hard drive, RAM, VGA, Motherboard or any other hardware. This is usually happen when you connect USB device to Windows Computer. You can see that massage as below picture.

**Table of Contents**	
Solution 01 : Use hardware and device troubleshooter
Solution 02: Uninstall drivers to fix USB device not recognized error
Solution 03: Change USB selective suspend settings
Solution 04: Unplug your power supply to fix USB device not recognized error
Solution 05: Disable and Re-enable USB hub device
Solution 06: Restart your computer

Read now : https://bigfactreview.com/how-to-fix-usb-device-not-recognized/

**Comment by Omkarcoder** [comment]
Hi may I know what type of USB device do you have. Like USB 2.0 or 3.0? And what computer system do you have! where you are trying to use it!
