### ISSUE TITLE
feature request: apply topics to multiple repositories at a time

### ISSUE THREAD

**Issue by spdegabrielle** [github/explore#908]
Applying topics to multiple repositories is slow and cumbersome. Functionality to apply a topic to multiple repositories would be very helpful.

**Comment by lukebates7** [comment]
Sorry how do I take it back please won't do it again

**Comment by ringsey008007** [comment]
Plz kick me

**Comment by shioucxi96** [comment]
？？？

**Comment by kenyonj** [comment]
Hi @spdegabrielle  ,
This repository is for creating and editing content on github.com/topics and github.com/collections. If you have feature requests please consider opening a thread on https://github.community/.

Thanks!
